baseURL = "https://bschen.tw/"
languageCode = "zh-cmn-Hant"
title = "Lorem Ipsum"
theme = "hugo-bingo"

enableEmoji = true
footnoteReturnLinkContents = "↩"
hasCJKLanguage = true

disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

[permalinks]
  post = "/posts/:slug/"

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true

[languages]

  [languages.en]
    weight = 20
    languageCode = "en-us"
    languageName = "English"
    contentDir = "content/en"

  [languages.zh]
    weight = 10
    languageCode = "zh-tw"
    languageName = "中文（臺灣）"
    contentDir = "content/zh"

[menu]

  [[languages.en.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/en"
    weight = 10

  [[languages.en.menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/en/posts"
    weight = 20

  [[languages.zh.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[languages.zh.menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 20

[params]
  themeColor = "default"
  dateFormat = "2006-01-02"
  mainSections = ["post"]

  [params.gravatar]
    email = "hi@bschen.tw"

  [[params.social]]
    name = "github"
    url = "https://github.com/gundamew"
    weight = 10

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bschen"
    weight = 20

  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/story/bschen"
    weight = 30

  [[params.social]]
    name = "rss"
    url = "https://blog.bschen.tw/feed"
    weight = 40
